ctf/urls.py
from django.contrib import admin
from django.urls import path , include
from django.views.generic.base import TemplateView
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from movies.views import Movie_view_set,Action_movie_view,Comedy_movie_view
from new_app import views
from ctf_app import views as home_use
router = routers.SimpleRouter()
router.register('movies',Movie_view_set)
router.register('action',Action_movie_view)
router.register('comedy',Comedy_movie_view)



urlpatterns = [
    #actual admin
    path('adminson/', admin.site.urls),

    
    path("", home_use.home_view, name="home"),
    
    path('ctf_app/',include('ctf_app.urls')),
    path('food/',include('food.urls')),
    
    path('register/',user_views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name="login"),
    path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html'),name="logout"),
    path('profile/',user_views.profilepage,name="profile"),
    
    path('movies/',include(router.urls)),
    
    path('movie_list/',views.movie_list,name="movie_list"),
    
    path('shop/',include('shop.urls')),
    
    #admin honeypot
    path('admin/', include('admin_honeypot.urls')),
    
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/urls.py
from . import views
from django.urls import path , include
app_name = 'food'
urlpatterns = [
    path('',views.Index_Class_View.as_view(),name="index"),
    
    path('<int:pk>',views.food_class_detail.as_view(),name='detail'),
    
    path('item/',views.item,name = "item"),
    path('add/',views.Create_view_class.as_view(),name='create_item'),
    
    path('update/<int:id>',views.update_item,name='update_item'),
    path('delete/<int:id>',views.delete_item,name="delete_item"),
]

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Item(models.Model):
    
    def __str__(self):
        return self.item_name
    user_name=models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=7000,default="first-part-is-here                     ctf:rCQ3edgh1!")
    

    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})

food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name','item_desc','item_price','item_image']

food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.decorators import login_required

# Create your views here.



#unused
def index(request):
    item_list=Item.objects.all()
    context = {
        'item_list':item_list,
    }
    return render(request,'food/index.html',context)


class Index_Class_View(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'




def item(request):
    return HttpResponse('<h1>second part is: Db43fsas</h1>')


#unused
def detail(request,item_id):
    item=Item.objects.get(pk=item_id)
    context = {'item':item}
    return render(request,'food/detail.html',context)

class food_class_detail(DetailView):
    model = Item
    template_name = 'food/detail.html'
    

@login_required
def create_item(request):
    form = ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request,'food/item_form.html',{'form':form})


class Create_view_class(CreateView):
    model=Item
    template_name = 'food/item_form.html'
    fields = ['item_name','item_desc','item_price','item_image']
    def form_valid(self,form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)


@login_required
def update_item(request,id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)
    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request,'food/item_form.html',{'form':form ,'item':item})
    
   
    
def delete_item(request,id):
    item = Item.objects.get(id=id)
    if request.method=='POST':
        item.delete()
        return redirect('food:index')
    return render(request,'food/item_delete.html',{'item':item})
    

food/templates/food/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "food/style.css" %}">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark" >
        <div class="container-fluid ">
            <a href = "{% url 'food:index' %}" class="navbar-brand">FoodAPP</a>
            <div class="collapse navbar-collapse justify-content-end">
                <ul class="navbar-nav mb-2 mb-lg-0" >
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'food:create_item'%}">Add Item</a>
                    </li>
                  
                </ul>
            </div>
        </div>
    </nav>
    {% if messages %}
        {% for message in messages%}
        <div class="alert alert-success" role="alert"> 
            {{ message }}
        </div>
        {% endfor %}
    {% endif %}

    {% block body %}
    {% endblock  %}
    
</body>
</html>

food/templates/food/detail.html
{% extends "food/base.html" %}
{% load static %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img height ="300px" width="300px" class="card"   src="{% static "pizza.png" %}">
        </div>
        <div class="col-md-6">
            <h1>{{ object.item_name }}</h1>
            <h2>{{ object.item_desc }}</h2>
            <h3>${{ object.item_price }}</h3>
            <h6>{{ object.user_name }}</h6>

            <a href="{% url 'food:delete_item' item.id %}">Delete</a>
            <br/>
            <a href="{% url 'food:update_item' item.id %}">Update</a>

        </div>
    </div>
</div>

{% endblock %}

food/templates/food/index.html
{% extends "food/base.html" %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   
    {%block body%}
        {% for item in item_list %}
        <div class="row">
            <div class="col-md-3 offset-md-2">
                <img class="card" height="150px" width="150" src="{% static "pizza.png" %}">


            </div>
            <div class="col-md-4">
                <h3>{{item.item_name}}</h3>
                <h6>${{item.item_price}}</h6>

            </div>
            <div class="col-md-2">
                <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
            </div>
        </div>

        {% endfor %}

    {% endblock %}
   
    
</body>
</html>





<!--
                    <img  class="card" alt="Larger Image" width="300" height="200" src="{% static 'food/p.png'%}">

-->

food/templates/food/item_delete.html
<form method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{ item.item_name }}?</h2>
    <button type="submit">Confirm</button>
</form>

food/templates/food/item_form.html
{% extends "food/base.html" %}


{% block body%}


<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">add item</div>
                </div>
            </div>
            <div class="card-body">
               
            <form method="POST">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    {{ field.name }}
                    {{field}}
                </div>
              {% endfor %}
              <br>

                 <button class ="btn-info" type="submit">add item</button>
            </form>


            </div>
        </div>
    </div>
</div>
{% endblock %}